# docker-compose.yml
version: '3.8'
volumes:
  orderdb_vol:

networks:
  micro_network:
    external:
      name: micro_network

services:
  order-api:
    container_name: corder-service
    build:
      context: .
    ports:
    - "5003:5003"
    depends_on:
      - order-db
    networks:
      - micro_network
    restart: always
  order-db:
    container_name: corder_dbase
    image: postgres:latest
    ports:
    - "5434:5432"
    environment:
      POSTGRES_USER: postgres3
      POSTGRES_PASSWORD: Mango44
      POSTGRES_DB: order
    networks:
      - micro_network
    volumes:
    - orderdb_vol:/var/lib/postgresql/data
    - ./initdb-order.sql:/docker-entrypoint-initdb.d/initdb-order.sql